/* Theme-editor logic: editable token lists, color/contrast math, and live CSS
 * generation. The kit's spacing/radius primitives are defined so the token's
 * numeric suffix equals its px base (--ds-spacing-4: 4px), so a global multiplier
 * is just `suffix × scale` — no edits to the generated token file required. */

export type Brand = "jit" | "randstadt";

// ── Editable semantic colors (shadcn names verbatim) ────────────────────────
export type ColorToken = {
  /* the --ds-color-<key> custom property */
  key: string;
  label: string;
  group: string;
};

export const COLOR_TOKENS: ColorToken[] = [
  { key: "background", label: "Background", group: "Base" },
  { key: "foreground", label: "Foreground", group: "Base" },
  { key: "primary", label: "Primary", group: "Primary" },
  { key: "primary-foreground", label: "Primary fg", group: "Primary" },
  { key: "secondary", label: "Secondary", group: "Secondary" },
  { key: "secondary-foreground", label: "Secondary fg", group: "Secondary" },
  { key: "muted", label: "Muted", group: "Muted" },
  { key: "muted-foreground", label: "Muted fg", group: "Muted" },
  { key: "accent", label: "Accent", group: "Accent" },
  { key: "accent-foreground", label: "Accent fg", group: "Accent" },
  { key: "card", label: "Card", group: "Surfaces" },
  { key: "card-foreground", label: "Card fg", group: "Surfaces" },
  { key: "popover", label: "Popover", group: "Surfaces" },
  { key: "popover-foreground", label: "Popover fg", group: "Surfaces" },
  { key: "destructive", label: "Destructive", group: "Status" },
  { key: "destructive-foreground", label: "Destructive fg", group: "Status" },
  { key: "border", label: "Border", group: "UI" },
  { key: "input", label: "Input", group: "UI" },
  { key: "ring", label: "Ring", group: "UI" },
];

// fg / bg pairs to check for WCAG contrast
export const CONTRAST_PAIRS: { label: string; fg: string; bg: string }[] = [
  { label: "Text on background", fg: "foreground", bg: "background" },
  { label: "Text on card", fg: "card-foreground", bg: "card" },
  { label: "Text on popover", fg: "popover-foreground", bg: "popover" },
  { label: "Primary button", fg: "primary-foreground", bg: "primary" },
  { label: "Secondary button", fg: "secondary-foreground", bg: "secondary" },
  { label: "Muted text", fg: "muted-foreground", bg: "muted" },
  { label: "Accent", fg: "accent-foreground", bg: "accent" },
  { label: "Destructive", fg: "destructive-foreground", bg: "destructive" },
];

// ── Spacing & radius primitive suffixes (px base == suffix) ─────────────────
export const SPACING_SUFFIXES = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 56, 64,
  80, 96, 128, 160, 192, 256,
];
export const RADIUS_SUFFIXES = [2, 4, 6, 8, 12, 16, 24];

export type ThemeState = {
  brand: Brand;
  colors: Record<string, string>; // key -> hex override
  spacingScale: number;
  radiusScale: number;
};

export const DEFAULT_STATE: ThemeState = {
  brand: "jit",
  colors: {},
  spacingScale: 1,
  radiusScale: 1,
};

// round to 0.1px to avoid sub-pixel noise
const px = (n: number) => `${Math.round(n * 10) / 10}px`;

/** The CSS that applies the current edits live. Must target `:root` (default):
 * every token is declared at :root and alias chains (e.g. button-fill →
 * color-primary) resolve there, so overrides only cascade when applied at :root —
 * the same reason brand switching sets data-theme on <html>. */
export function generateOverrideCss(state: ThemeState, selector = ":root"): string {
  const lines: string[] = [];

  for (const { key } of COLOR_TOKENS) {
    const v = state.colors[key];
    if (v) lines.push(`  --ds-color-${key}: ${v};`);
  }

  if (state.spacingScale !== 1) {
    for (const n of SPACING_SUFFIXES) lines.push(`  --ds-spacing-${n}: ${px(n * state.spacingScale)};`);
  }
  if (state.radiusScale !== 1) {
    for (const n of RADIUS_SUFFIXES) lines.push(`  --ds-borderradius-${n}: ${px(n * state.radiusScale)};`);
  }

  if (!lines.length) return "";
  return `${selector} {\n${lines.join("\n")}\n}`;
}

/** Standalone CSS for export (targets :root, includes a header). */
export function exportCss(state: ThemeState): string {
  const body = generateOverrideCss(state, ":root");
  const header = [
    "/* Kraken UI Kit — theme generated by the theme editor.",
    ` * Base brand: ${state.brand}  |  spacing ×${state.spacingScale}  |  radius ×${state.radiusScale}`,
    " * Paste after tokens.css to override. Colors edit the semantic layer;",
    " * spacing/radius rescale the primitives (everything downstream cascades). */",
  ].join("\n");
  return body ? `${header}\n${body}\n` : `${header}\n/* no changes from base ${state.brand} theme */\n`;
}

/** JSON snapshot for export / re-import. */
export function exportJson(state: ThemeState): string {
  return JSON.stringify(
    { brand: state.brand, spacingScale: state.spacingScale, radiusScale: state.radiusScale, colors: state.colors },
    null,
    2,
  );
}

// ── Color parsing & WCAG contrast ───────────────────────────────────────────
export function parseRgb(s: string): [number, number, number] | null {
  const m = s.match(/rgba?\(([^)]+)\)/);
  if (m) {
    const [r, g, b] = m[1].split(",").map((x) => parseFloat(x));
    return [r, g, b];
  }
  const hex = s.trim().replace("#", "");
  if (/^[0-9a-f]{6}$/i.test(hex)) {
    return [parseInt(hex.slice(0, 2), 16), parseInt(hex.slice(2, 4), 16), parseInt(hex.slice(4, 6), 16)];
  }
  if (/^[0-9a-f]{3}$/i.test(hex)) {
    return [parseInt(hex[0] + hex[0], 16), parseInt(hex[1] + hex[1], 16), parseInt(hex[2] + hex[2], 16)];
  }
  return null;
}

export function rgbToHex([r, g, b]: [number, number, number]): string {
  const h = (n: number) => Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, "0");
  return `#${h(r)}${h(g)}${h(b)}`;
}

function luminance([r, g, b]: [number, number, number]): number {
  const a = [r, g, b].map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * a[0] + 0.7152 * a[1] + 0.0722 * a[2];
}

export function contrastRatio(fg: string, bg: string): number | null {
  const a = parseRgb(fg);
  const b = parseRgb(bg);
  if (!a || !b) return null;
  const l1 = luminance(a);
  const l2 = luminance(b);
  const [hi, lo] = l1 > l2 ? [l1, l2] : [l2, l1];
  return Math.round(((hi + 0.05) / (lo + 0.05)) * 100) / 100;
}

export type WcagLevel = "AAA" | "AA" | "AA Large" | "Fail";
export function wcagLevel(ratio: number): WcagLevel {
  if (ratio >= 7) return "AAA";
  if (ratio >= 4.5) return "AA";
  if (ratio >= 3) return "AA Large";
  return "Fail";
}
